name: Keift OS
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  - type: flatpak
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox

  - type: script
    scripts:
      - init.sh
