name: Build

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login into GitHub Containers Registry
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: İmaj Adını Küçük Harfe Çevir (GHCR kuralı)
        run: echo "IMAGE_ID=$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: bootc İmajını İnşa Et (Build)
        run: podman build -t ${{ env.IMAGE_ID }}:latest -f ./Containerfile ./

      - name: İmajı Yükle (Push)
        run: podman push ${{ env.IMAGE_ID }}:latest
