name: Build

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  VERSION: 1
  FEDORA_VERSION: 44

jobs:
  image:
    if: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          push: true
          file: ./Containerfile
          context: ./
          platforms: linux/amd64,linux/arm64

  iso:
    # needs: image

    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Pull image
        run: sudo podman pull ghcr.io/${{ github.repository }}:latest

      - name: Create config
        run: |
          mkdir -p ./dist

          tee ./dist/config.toml &>/dev/null << EOF
          [customizations.installer.kickstart]
          contents = """
          graphical
          rootpw --lock
          """

          [customizations.installer.modules]
          enable = [
            "org.fedoraproject.Anaconda.Modules.Localization",
            "org.fedoraproject.Anaconda.Modules.Timezone"
          ]

          [customizations.iso]
          volume_id = "KEIFT-OS"
          EOF

      - name: Build it
        run: |
          sudo podman run \
            --rm \
            --privileged \
            -v ./dist/config.toml:/config.toml \
            -v ./dist:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            --rootfs ext4 \
            ghcr.io/${{ github.repository }}:latest

          sudo chown -R $USER:$USER ./dist

      - name: Inject into ISO
        run: |
          mkdir -p ./dist/inject/etc/anaconda/conf.d

          tee ./dist/inject/etc/anaconda/conf.d/99-keift-os.conf &>/dev/null << EOF
          [User Interface]
          hidden_spokes = UserSpoke,PasswordSpoke
          EOF

          sudo apt install -y xorriso cpio

          cd ./dist/inject
          find ./ -mindepth 1 | cpio -c -o | gzip -9 > ../inject.img.gz
          cd ../../

          xorriso \
            -indev ./dist/bootiso/install.iso \
            -outdev ./dist/keift-os-${{ matrix.arch }}.iso \
            -map ./dist/inject.img.gz /images/product.img \
            -boot_image any replay

          rm -rf ./dist/bootiso ./dist/inject ./dist/inject.img.gz

      - name: Generate checksum file
        run: sha256sum ./dist/keift-os-${{ matrix.arch }}.iso > ./dist/keift-os-${{ matrix.arch }}.iso-CHECKSUM

      - name: Upload to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            ./dist/keift-os-${{ matrix.arch }}.iso \
            s3://${{ secrets.R2_BUCKET_NAME }}/keift-os-${{ matrix.arch }}.iso

          aws s3 cp \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            ./dist/keift-os-${{ matrix.arch }}.iso-CHECKSUM \
            s3://${{ secrets.R2_BUCKET_NAME }}/keift-os-${{ matrix.arch }}.iso-CHECKSUM
